// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/16/2025, 12:39:57 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/elijahmusaally/Desktop/gitbubl/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/elijahmusaally/Desktop/gitbubl/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/elijahmusaally/Desktop/gitbubl/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/elijahmusaally/Desktop/gitbubl/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/elijahmusaally/Desktop/gitbubl/src/plugins/**/*.{js,ts,mjs}","/Users/elijahmusaally/Desktop/gitbubl/src/src/**/**/*.{js,ts,mjs}","/Users/elijahmusaally/Desktop/gitbubl/src/composables/**/*.{js,ts,mjs}","/Users/elijahmusaally/Desktop/gitbubl/src/utils/**/*.{js,ts,mjs}","/Users/elijahmusaally/Desktop/gitbubl/src/pages/about.vue","/Users/elijahmusaally/Desktop/gitbubl/src/pages/index.vue","/Users/elijahmusaally/Desktop/gitbubl/src/pages/signup.vue","/Users/elijahmusaally/Desktop/gitbubl/src/pages/[...404].vue","/Users/elijahmusaally/Desktop/gitbubl/src/pages/[username].vue","/Users/elijahmusaally/Desktop/gitbubl/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/elijahmusaally/Desktop/gitbubl/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/elijahmusaally/Desktop/gitbubl/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;